# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
- alignment: left
  newline: true
  segments:
  - background: "#a313a8"
    foreground: "#FFEB3B"
    style: diamond
    template:  ⚡ 
    trailing_diamond: "\ue0b0"
    type: root
  - background: p:green
    foreground: "#ffffff"
    leading_diamond: "<transparent,p:green>\ue0b0</>"
    style: diamond
    template: "{{ if .WSL }} WSL at{{ end }} {{.Icon}} "
    trailing_diamond: "\ue0b0"
    type: os
  - background: p:indigo
    foreground: "#ffffff"
    leading_diamond: "<transparent,p:indigo>\ue0b0</>"
    properties:
      folder_icon: ...
      folder_separator_icon: "<transparent> \ue0bd </>"
      home_icon: "\ueb06"
      style: full
    style: diamond
    template: " {{ .Path }} "
    trailing_diamond: "\ue0b0"
    type: path
  - background: "#00C853"
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}"
    - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
    - "{{ if gt .Behind 0 }}#B388FF{{ end }}"
    foreground: "#000000"
    powerline_symbol: "\ue0b0"
    properties:
      fetch_stash_count: true
      fetch_status: true
    style: powerline
    template: " {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00> \uf046 {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    type: git
  - background: "#910000"
    foreground: "#ffffff"
    powerline_symbol: "\ue0b0"
    style: powerline
    template: "<transparent> \uf12a</> {{ reason .Code }} "
    type: status
  type: prompt
- alignment: right
  segments:
  - background: p:indigo
    foreground: "#43CCEA"
    leading_diamond: "\ue0ba"
    min_width: 80
    properties:
      command: whoami
      shell: bash
    style: diamond
    template: " {{ .Output }}"
    trailing_diamond: "<transparent> \ue0bd </>"
    type: command
  - background: p:indigo
    foreground: "#43CCEA"
    style: diamond
    template: "{{ .HostName }} "
    trailing_diamond: "\ue0bc"
    type: session
  - background: p:indigo
    foreground: "#3EC669"
    leading_diamond: "\ue0ba"
    properties:
      time_format: "15:04:05"
    style: diamond
    template: " {{ .CurrentDate | date .Format }} "
    type: time
  type: prompt
- alignment: left
  newline: true
  segments:
  - foreground: "#ffffff"
    foreground_templates:
    - "{{ if gt .Code 0 }}#ff0000{{ end }}"
    properties:
      always_enabled: true
    style: plain
    template: ❯ 
    type: status
  type: prompt
console_title_template: "{{if .Root}} ⚡ {{end}}{{.Folder | replace \"~\" \"🏚\" }} @ {{.HostName}}"
palette:
  green: "#5e8c61"
  indigo: "#01396C"
transient_prompt:
  background: transparent
  foreground: "#ffffff"
  template: ❯ 
version: 2

