# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: shell
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        background: "p:sh-bg"
        foreground: "p:sh-fg"
        properties:
          mapped_shell_names:
            pwsh: PS
      - type: os
        style: powerline
        powerline_symbol: ""
        background: "p:os-bg"
        foreground: "p:os-fg"
      - type: text
        style: powerline
        powerline_symbol: ""
        foreground: "#ffffff"
        background: "p:imms-green"
        template: "{{ if .Env.JUNEST_ENV }} junest {{ end }}"
      - type: path
        style: powerline
        powerline_symbol: ""
        foreground: "p:path-fg"
        background: "p:path-bg"
        properties:
          style: full
      - type: git
        style: powerline
        powerline_symbol: ""
        template: " {{ .HEAD }}{{ if or .Working.Changed .Staging.Changed }}*{{ end }} {{ if gt .Behind 0 }}{{.Behind}}{{ end }}{{ if gt .Ahead 0 }}{{.Ahead}}{{ end }} "
        foreground: "p:text"
        background: "p:imms-green"
        background_templates:
          - "{{ if (.Staging.Changed) }}p:git-warn{{ end }}"
          - "{{ if (.Working.Changed) }}p:git-alert{{ end }}"
          - "{{ if or (gt .Ahead 0) (gt .Behind 0) }}p:git-info{{ end }}"
        properties:
          fetch_status: true
          branch_icon: ""
          commit_icon: "@"
      - type: python
        style: powerline
        powerline_symbol: ""
        foreground: "p:text"
        background: "red"
        template: "  {{ .Full }} {{ .Major }}"
        properties:
          home_enabled: true
  - type: prompt
    alignment: right
    overflow: hide
    segments:
      - type: command
        style: diamond
        leading_diamond: ""
        trailing_diamond: "\ue0bc"
        foreground: "p:text"
        background: "p:time"
        template: " {{ .Output }} "
        properties:
          shell: bash
          command: "hostname"
      - type: time
        style: diamond
        leading_diamond: "\ue0ba"
        trailing_diamond: " "
        foreground: "p:text"
        background: "p:time"
        properties:
          time_format: 15:04:05
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground: "#ffffff"
        template: '❯'
  - type: rprompt
    alignment: left
    segments:
      - type: executiontime
        style: plain
        foreground: "p:imms-gray"
        background: transparent
        template: " {{.FormattedMs }} "
        properties:
          threshold: 100
          style: austin
          always_enabled: false
palettes:
  template: "imms"
  list:
    imms:
      # IMMS RGB palette
      imms-blue:         "#002D7D"
      imms-lightblue:    "#7896C8"
      imms-gray:         "#A5A5A5"
      imms-grey:         "p:imms-gray"
      imms-green:        "#8BA70A"
      imms-red:          "#870A1E"
      # IMMS Inkscape palette
      imms-sapphireblue: "#034964"
      imms-signalblue:   "#005BAA"
      imms-farblue:      "#6C8CC7"
      imms-darksky:      "#95B6DF"
      imms-pastelblue:   "#C7D6EE" 
      imms-telegray:     "#C7C8CA"
      imms-telegrey:     "p:imms-lightgray"
      imms-rubyred:      "#C9252C"
      imms-greenyellow:  "#B2D235"
      imms-yellowgreen:  "#7EA831"
      imms-leafgreen:    "#54771E"
      # semantic mapping
      rob-red: "#EE0000"
      rob-orange: "#AADD00"
      rob-yellow: "#AADD00"
      path: "p:imms-blue"
      text: "p:imms-telegrey"
      time: "p:imms-leafgreen"
      host: "p:imms-green"
      git-alert: "p:rob-red"
      git-warn: "p:rob-orange"
      git-info: "p:rob-yellow"
      path-bg: "p:imms-blue"
      path-fg: "p:imms-telegray"
      os-bg: "p:imms-sapphireblue"
      os-fg: "p:imms-telegray"
      sh-bg: "p:imms-signalblue"
      sh-fg: "p:imms-telegray"
    side:
      path: "#0000ff"
      text: "#ffffff"
transient_prompt:
  background: transparent
  foreground: "p:text"
  template: '❯ '
